name: comment-bot
on:
  issue_comment:
    types:
      - created

jobs:
  parse:
    if: ${{ github.event.issue.number == 1 }}
    name: Check for chatbot commands
    runs-on: ubuntu-latest
    outputs:
      gen-test-ticket: ${{ steps.comvent.outputs.gen-test-ticket }}

    steps:
      - name: Handle with Comvent
        uses: rytswd/comvent@v0.3
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comvent-chatbot.yaml

  reply:
    runs-on: ubuntu-latest
    name: Respond to /test-for
    needs: parse
    if: always() && needs.parse.outputs.gen-test-ticket
    steps:
      - name: Reply and file ticket
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `Command \`/test-for\` was triggered by the comment. ${{steps.comvent.outputs.gen-test-ticket}}`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })

      - uses: hmarr/debug-action@v2
