name: comment-bot
on:
  issue_comment:
    types:
      - created

jobs:
  comment-bot:
    if: ${{ github.event.issue.number == 1 }}
    name: Respond to test contributions
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/debug-action@v2
      - name: Handle with Comvent
        uses: rytswd/comvent@v0.3
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comvent-chatbot.yaml

      - if: steps.comvent.outputs.gen-test-ticket != ''
        name: Handle comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `Command \`/test-for\` was triggered by the comment. ${{steps.comvent.outputs.gen-test-ticket}}`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
